 # Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.61.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

#
# Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
#             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
#
lane :beta do |values|
  # Fabric generated this lane for deployment to Crashlytics Beta
  # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
  gym(scheme: 'simpleTodo', export_method: 'ad-hoc')

  emails = values[:test_email] ? values[:test_email] : ['north1602@gmail.com'] # You can list more emails here
  groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

  crashlytics(api_token: '8f57ef139f803875850357d191431a0200318f3f',
           build_secret: '08f10171cd8111d9849b232ac117584f306b08390a3c1b4799e9b0b2e075230a',
                 emails: emails,
                 groups: groups,
                  notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
          notifications: true) # Should this distribution notify your testers via email?

  # for all available options run `fastlane action crashlytics`

  # You can notify your team in chat that a beta build has been uploaded
  # slack(
  #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
  #   channel: "beta-releases",
  #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
  # )
end

lane :release do
  match
  disable_automatic_code_signing(path: "simpleTodo.xcodeproj")
  gym
  enable_automatic_code_signing(path: "simpleTodo.xcodeproj")
  pilot
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
